servers:
    - name: server1
      address: localhost
      port: 8080

    - name: server2
      address: localhost
      port: 8081

    - name: server3
      address: localhost
      port: 8083

    - name: debugServer
      address: localhost
      port: 8082